# Generated by Django 4.1.5 on 2023-01-15 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('providerType', models.CharField(blank=True, max_length=30)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('afm', models.CharField(blank=True, max_length=20, null=True)),
                ('workers', models.IntegerField(blank=True, default=0, null=True)),
                ('country', models.CharField(blank=True, max_length=30)),
                ('street', models.CharField(blank=True, max_length=30)),
                ('postal', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('identification', models.CharField(blank=True, max_length=30)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Intership',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('university', models.CharField(blank=True, max_length=200, null=True)),
                ('lenght', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=30)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
