# Generated by Django 4.1.5 on 2023-01-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_internship_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
