# Generated by Django 4.1 on 2023-01-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_apply_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='companyName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
