# Generated by Django 4.1 on 2023-01-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_internship_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
